### ISSUE TITLE
'WSGIRequest' object has no attribute 'user_agent'

### ISSUE THREAD

**Issue by lowegreg** [selwin/django-user_agents#31]
If anyone can help with this error I'd be very appreciative.  I think I have the settings correct:

> INSTALLED_APPS = (
>    '... Lots of apps',
>    'django_user_agents'
> )
> 

> MIDDLEWARE_CLASSES = (
>     '... Lots of middleware',
>     'django_user_agents.middleware.UserAgentMiddleware'
> )

`Traceback (most recent call last):
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/Greg/Development/propel/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/Greg/Google Drive/Propel/PropelSurveySolutions/questionnaire/views.py", line 42, in post
    print self.request.user_agent.is_mobile
AttributeError: 'WSGIRequest' object has no attribute 'user_agent'`

**Comment by goobie** [comment]
Check if AuthenticationMiddleware is missing from your middleware classes.

**Comment by Kalightortaio** [comment]
I have the same error, and it's not missing

**Comment by meibassam** [comment]
Also same error here  !! 
Still bug not fixed ?

**Comment by Tamupiwa** [comment]
My middleware and installed_apps settings are set but still getting this error as well!

**Comment by Mujirin** [comment]
I get the same error
